### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by acmh** [dsalahutdinov/yabeda-http_requests#1]
# What did you do?

Just put the gem on the Gemfile

# What did you expect to happen?

I expected a correct install of the gem

# What actually happened?

/usr/local/bundle/gems/sniffer-0.4.0/lib/sniffer.rb:70:in `require_relative': /usr/local/bundle/gems/sniffer-0.4.0/lib/sniffer/adapters/httpclient_adapter.rb:34: syntax error, unexpected keyword_rescue, expecting keyword_end (SyntaxError)
        rescue HTTPClient::RetryableResponse
              ^
/usr/local/bundle/gems/sniffer-0.4.0/lib/sniffer/adapters/httpclient_adapter.rb:34: syntax error, unexpected =>
TPClient::RetryableResponse => e
                              ^
/usr/local/bundle/gems/sniffer-0.4.0/lib/sniffer/adapters/httpclient_adapter.rb:55: syntax error, unexpected keyword_end, expecting end-of-input

# Additional context

It seems a problem with sniffer gem, but I consider put it here to give awareness of this problem

Thanks for your time and amazing gem!

# Environment

Ruby Version:
2.4.5

Framework Version (Rails, whatever):
Rails 4.2.11.1

Sniffer Version:
0.4.0

**Comment by Envek** [comment]
Hey! Sorry for such a late reply!

Sniffer uses syntax added in Ruby 2.5 (`rescue` in blocks), so either downgrade sniffer version or upgrade your Ruby.

As Ruby 2.4 is already reached its EOL in 2020, I decided to drop support for it and in the next version `yabeda-http_requests` will require at least Ruby 2.5.
